"""Add content_hash and fts_vector for Hybrid Search

Revision ID: 168dab471052
Revises: feb428baf05c
Create Date: 2026-06-28 19:29:29.666485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '168dab471052'
down_revision: Union[str, Sequence[str], None] = 'feb428baf05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('fts_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_document_chunks_fts', 'document_chunks', ['fts_vector'], unique=False, postgresql_using='gin')
    op.add_column('documents', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'content_hash')
    op.drop_index('ix_document_chunks_fts', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'fts_vector')
    # ### end Alembic commands ###
