"""Add Workspace and User Roles for RBAC

Revision ID: feb428baf05c
Revises: 8f5b14e5e473
Create Date: 2026-06-28 19:26:03.470253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb428baf05c'
down_revision: Union[str, Sequence[str], None] = '8f5b14e5e473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.add_column('documents', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'])
    
    # Create the ENUM type explicitly for PostgreSQL
    role_enum = sa.Enum('admin', 'editor', 'viewer', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('role', role_enum, server_default='viewer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Drop the enum type
    sa.Enum('admin', 'editor', 'viewer', name='role').drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
